name: Go

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go: ["1.16", "1.18"]
      fail-fast: false
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v3.3.0
        with:
          go-version: ${{ matrix.go }}
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
